# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163FtZ3FNecGmtj1SCXWLy4WemMFP05hL
"""



import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import streamlit as st

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="MPT Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&family=JetBrains+Mono:wght@400;600&display=swap');

    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    .main { background-color: #0d1117; }

    .metric-card {
        background: #161b22;
        border: 1px solid #30363d;
        border-radius: 10px;
        padding: 1.2rem 1.5rem;
        text-align: center;
    }
    .metric-label {
        font-size: 0.75rem;
        color: #8b949e;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        margin-bottom: 0.3rem;
        font-weight: 600;
    }
    .metric-value {
        font-family: 'JetBrains Mono', monospace;
        font-size: 1.6rem;
        font-weight: 700;
        color: #58a6ff;
    }
    .metric-value.positive { color: #3fb950; }
    .metric-value.negative { color: #f85149; }
    .metric-value.neutral  { color: #58a6ff; }

    .section-header {
        font-size: 0.7rem;
        font-weight: 700;
        color: #8b949e;
        text-transform: uppercase;
        letter-spacing: 0.12em;
        margin: 1.5rem 0 0.8rem 0;
        border-bottom: 1px solid #21262d;
        padding-bottom: 0.4rem;
    }

    div[data-testid="stSidebar"] {
        background: #0d1117;
        border-right: 1px solid #21262d;
    }

    .stSelectbox label, .stSlider label, .stRadio label {
        color: #8b949e !important;
        font-size: 0.8rem !important;
        font-weight: 600 !important;
        text-transform: uppercase;
        letter-spacing: 0.06em;
    }
</style>
""", unsafe_allow_html=True)

# ── Plotly dark theme base ────────────────────────────────────────────────────
PLOT_THEME = dict(
    plot_bgcolor="#0d1117",
    paper_bgcolor="#0d1117",
    font=dict(family="Inter", color="#c9d1d9", size=12),
    xaxis=dict(gridcolor="#21262d", linecolor="#30363d", zerolinecolor="#21262d"),
    yaxis=dict(gridcolor="#21262d", linecolor="#30363d", zerolinecolor="#21262d"),
    legend=dict(bgcolor="#161b22", bordercolor="#30363d", borderwidth=1),
)

# ── Load data ─────────────────────────────────────────────────────────────────
@st.cache_data
def load_data():
    prices  = pd.read_csv("stock_prices.csv",  index_col=0, parse_dates=True)
    returns = pd.read_csv("stock_returns.csv", index_col=0, parse_dates=True)
    return prices, returns

@st.cache_data
def compute_frontier(returns_matrix, mean_returns, cov_matrix, N=100_000, seed=42):
    np.random.seed(seed)
    n = returns_matrix.shape[1]
    raw = np.random.random((N, n))
    W   = raw / raw.sum(axis=1, keepdims=True)

    port_ret = W @ mean_returns
    port_ret_annual = ((1 + port_ret)**12 - 1) * 100
    port_var = np.einsum('ij,jk,ik->i', W, cov_matrix, W)
    port_vol = np.sqrt(port_var * 12) * 100

    # Downside risk via semicovariance
    downside = np.minimum(returns_matrix - mean_returns, 0)
    Psi = (downside.T @ downside) / returns_matrix.shape[0]
    port_semivar = np.einsum('ij,jk,ik->i', W, Psi, W)
    port_semidev = np.sqrt(port_semivar * 12) * 100

    return W, port_ret_annual, port_vol, port_semidev, Psi

@st.cache_data
def compute_analytical(mean_returns, cov_matrix):
    n    = len(mean_returns)
    ones = np.ones(n)
    Sinv = np.linalg.inv(cov_matrix)
    A = ones @ Sinv @ mean_returns
    B = mean_returns @ Sinv @ mean_returns
    C = ones @ Sinv @ ones
    D = B*C - A**2
    g = (1/D)*(B*(Sinv@ones) - A*(Sinv@mean_returns))
    h = (1/D)*(C*(Sinv@mean_returns) - A*(Sinv@ones))
    return g, h, A, B, C, D

# ── Main ──────────────────────────────────────────────────────────────────────
prices, returns = load_data()
stocks = returns.columns.tolist()

returns_train = returns[returns.index < "2020-01-01"]
mean_ret  = returns_train.mean().values
cov_mat   = returns_train.cov().values
ret_mat   = returns_train.values

W, port_ret, port_vol, port_semidev, Psi = compute_frontier(ret_mat, mean_ret, cov_mat)
g, h, A, B, C, D = compute_analytical(mean_ret, cov_mat)

# Sidebar navigation
st.sidebar.markdown("## 📊 MPT Dashboard")
st.sidebar.markdown("---")
page = st.sidebar.radio("Navigate", [
    "📋 Overview",
    "🎯 Efficient Frontier",
    "⚖️ Portfolio Weights",
    "📈 Backtest",
    "📉 Rolling Sharpe",
    "🔻 Semivariance (Estrada)",
])
st.sidebar.markdown("---")
st.sidebar.markdown("**Training period:** 2010–2019")
st.sidebar.markdown("**Backtest period:** 2021–2025")
st.sidebar.markdown("**Universe:** 10 NSE stocks")
st.sidebar.markdown("**Risk-free rate:** 6.5% p.a.")

# ════════════════════════════════════════════════════════════════════════════
# PAGE 1 — OVERVIEW
# ════════════════════════════════════════════════════════════════════════════
if page == "📋 Overview":
    st.title("Modern Portfolio Theory")
    st.markdown("##### Nifty 50 Universe · 2010–2025 · 10 Stocks")
    st.markdown("---")

    # Summary stats
    summary = pd.DataFrame({
    "Ann. Return (%)":     (((1 + returns_train.mean())**12 - 1) * 100).round(2),
    "Ann. Volatility (%)": (returns_train.std() * np.sqrt(12) * 100).round(2),
    "Sharpe (rf=6.5%)":    ((((1 + returns_train.mean())**12 - 1) - 0.065) /
                             (returns_train.std() * np.sqrt(12))).round(3),
    "Min Monthly (%)":     (returns_train.min() * 100).round(2),
    "Max Monthly (%)":     (returns_train.max() * 100).round(2),
})

    # Top metrics row
    cols = st.columns(4)
    best = summary["Ann. Return (%)"].idxmax()
    safest = summary["Ann. Volatility (%)"].idxmin()
    best_sharpe = summary["Sharpe (rf=6.5%)"].idxmax()
    worst = summary["Ann. Return (%)"].idxmin()

    with cols[0]:
        st.markdown('<div class="metric-card"><div class="metric-label">Best Return</div>'
                    f'<div class="metric-value positive">{best}<br>{summary.loc[best,"Ann. Return (%)"]:.1f}%</div></div>',
                    unsafe_allow_html=True)
    with cols[1]:
        st.markdown('<div class="metric-card"><div class="metric-label">Lowest Volatility</div>'
                    f'<div class="metric-value neutral">{safest}<br>{summary.loc[safest,"Ann. Volatility (%)"]:.1f}%</div></div>',
                    unsafe_allow_html=True)
    with cols[2]:
        st.markdown('<div class="metric-card"><div class="metric-label">Best Sharpe</div>'
                    f'<div class="metric-value positive">{best_sharpe}<br>{summary.loc[best_sharpe,"Sharpe (rf=6.5%)"]:.2f}</div></div>',
                    unsafe_allow_html=True)
    with cols[3]:
        st.markdown('<div class="metric-card"><div class="metric-label">Lowest Return</div>'
                    f'<div class="metric-value negative">{worst}<br>{summary.loc[worst,"Ann. Return (%)"]:.1f}%</div></div>',
                    unsafe_allow_html=True)

    st.markdown("")

    # Summary table
    st.markdown('<div class="section-header">Stock Summary Statistics (2010–2019 Training Period)</div>',
                unsafe_allow_html=True)
    st.dataframe(summary.style.format("{:.2f}"), use_container_width=True)

    # Normalised price chart
    st.markdown('<div class="section-header">Normalised Price Performance (Base = 100)</div>',
                unsafe_allow_html=True)

    selected_stocks = st.multiselect("Select stocks to display", stocks, default=stocks)
    norm = (prices[selected_stocks] / prices[selected_stocks].iloc[0] * 100)

    fig = go.Figure()
    colors = px.colors.qualitative.Plotly
    for i, s in enumerate(selected_stocks):
        fig.add_trace(go.Scatter(x=norm.index, y=norm[s],
                                 name=s, line=dict(width=1.5, color=colors[i % len(colors)])))
    fig.update_layout(**PLOT_THEME, height=400,
                      xaxis_title="Date", yaxis_title="Normalised Price (Base=100)")
    st.plotly_chart(fig, use_container_width=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE 2 — EFFICIENT FRONTIER
# ════════════════════════════════════════════════════════════════════════════
elif page == "🎯 Efficient Frontier":
    st.title("Efficient Frontier")
    st.markdown("##### 100,000 Random Long-Only Portfolios · Analytical Solution Overlay")
    st.markdown("---")

    target_pct = st.slider("Target Annual Return (%)", 10.0, 30.0, 22.0, 0.5)
    mu_target  = (1 + target_pct/100)**(1/12) - 1
    w_target   = g + h * mu_target
    ret_target = ((1 + w_target @ mean_ret)**12 - 1) * 100
    vol_target = np.sqrt(w_target @ cov_mat @ w_target * 12) * 100

    # GMV
    mu_gmv = A / C
    w_gmv  = g + h * mu_gmv
    ret_gmv = ((1 + w_gmv @ mean_ret)**12 - 1) * 100
    vol_gmv = np.sqrt(w_gmv @ cov_mat @ w_gmv * 12) * 100

    # Individual stocks
    stock_ret = ((1 + mean_ret)**12 - 1) * 100
    stock_vol = np.sqrt(np.diag(cov_mat) * 12) * 100

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=port_vol, y=port_ret, mode="markers",
        marker=dict(size=1, color="#1f6feb", opacity=0.3),
        name="Simulated Portfolios", hoverinfo="skip"
    ))
    fig.add_trace(go.Scatter(
        x=stock_vol, y=stock_ret, mode="markers+text",
        marker=dict(size=10, color="white", symbol="diamond",
                    line=dict(color="black", width=1)),
        text=stocks, textposition="top right",
        textfont=dict(size=10, color="white"),
        name="Individual Stocks"
    ))
    fig.add_trace(go.Scatter(
        x=[vol_gmv], y=[ret_gmv], mode="markers",
        marker=dict(size=18, color="#58a6ff", symbol="star",
                    line=dict(color="white", width=1)),
        name=f"Global Min Variance ({ret_gmv:.1f}%, {vol_gmv:.1f}%)"
    ))
    fig.add_trace(go.Scatter(
        x=[vol_target], y=[ret_target], mode="markers",
        marker=dict(size=20, color="#3fb950", symbol="star",
                    line=dict(color="white", width=1)),
        name=f"Target Portfolio ({ret_target:.1f}%, {vol_target:.1f}%)"
    ))
    fig.update_layout(**PLOT_THEME, height=550,
                      xaxis_title="Annualised Volatility (%)",
                      yaxis_title="Annualised Expected Return (%)",
                      title=f"Efficient Frontier — Target Return: {target_pct:.1f}%")
    st.plotly_chart(fig, use_container_width=True)

    # Weights table
    st.markdown('<div class="section-header">Optimal Portfolio Weights</div>', unsafe_allow_html=True)
    wdf = pd.DataFrame({"Stock": stocks, "Weight (%)": (w_target * 100).round(2)})
    wdf["Type"] = wdf["Weight (%)"].apply(lambda x: "Long" if x >= 0 else "Short")

    col1, col2 = st.columns([1, 1])
    with col1:
        st.dataframe(wdf.set_index("Stock").style.format({"Weight (%)": "{:.2f}"}),
                     use_container_width=True)
    with col2:
        fig2 = go.Figure(go.Bar(
            x=wdf["Stock"], y=wdf["Weight (%)"],
            marker_color=["#3fb950" if w >= 0 else "#f85149" for w in wdf["Weight (%)"]],
        ))
        fig2.update_layout(**PLOT_THEME, height=300,
                           xaxis_title="Stock", yaxis_title="Weight (%)",
                           title="Portfolio Weights")
        st.plotly_chart(fig2, use_container_width=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE 3 — PORTFOLIO WEIGHTS
# ════════════════════════════════════════════════════════════════════════════
elif page == "⚖️ Portfolio Weights":
    st.title("Portfolio Weights Comparison")
    st.markdown("##### wp (22% Target) vs Global Minimum Variance Portfolio")
    st.markdown("---")

    mu_target = (1.22)**(1/12) - 1
    w_wp  = g + h * mu_target
    mu_gmv = A / C
    w_gmv = g + h * mu_gmv

    fig = go.Figure()
    fig.add_trace(go.Bar(name="wp (22% Target)", x=stocks, y=w_wp*100,
                         marker_color="#3fb950"))
    fig.add_trace(go.Bar(name="Min Variance", x=stocks, y=w_gmv*100,
                         marker_color="#58a6ff"))
    fig.update_layout(**PLOT_THEME, barmode="group", height=450,
                      xaxis_title="Stock", yaxis_title="Weight (%)",
                      title="Portfolio Weights: wp vs Global Min Variance")
    st.plotly_chart(fig, use_container_width=True)

    col1, col2 = st.columns(2)
    with col1:
        st.markdown('<div class="section-header">wp (22% Target)</div>', unsafe_allow_html=True)
        st.dataframe(pd.DataFrame({"Weight (%)": (w_wp*100).round(2)}, index=stocks),
                     use_container_width=True)
    with col2:
        st.markdown('<div class="section-header">Global Min Variance</div>', unsafe_allow_html=True)
        st.dataframe(pd.DataFrame({"Weight (%)": (w_gmv*100).round(2)}, index=stocks),
                     use_container_width=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE 4 — BACKTEST
# ════════════════════════════════════════════════════════════════════════════
elif page == "📈 Backtest":
    st.title("Backtest: 2021–2025")
    st.markdown("##### Buy-and-Hold vs Quarterly Rebalanced")
    st.markdown("---")

    strategy = st.radio("Strategy", ["Buy-and-Hold", "Quarterly Rebalanced"], horizontal=True)

    mu_target  = (1.22)**(1/12) - 1
    w_wp       = g + h * mu_target
    wp_ret_ann = ((1 + w_wp @ mean_ret)**12 - 1) * 100

    backtest_prices = prices[(prices.index >= "2021-01-01") & (prices.index <= "2025-06-30")]
    initial_capital = 100.0
    initial_prices  = backtest_prices.iloc[0].values

    if strategy == "Buy-and-Hold":
        shares = (initial_capital * w_wp) / initial_prices
        port_values = backtest_prices.values @ shares
    else:
        port_values = [initial_capital]
        shares = (initial_capital * w_wp) / initial_prices
        for i in range(1, len(backtest_prices)):
            cv = backtest_prices.iloc[i].values @ shares
            port_values.append(cv)
            if i % 3 == 0:
                shares = (cv * w_wp) / backtest_prices.iloc[i].values
        port_values = np.array(port_values)

    port_series = pd.Series(port_values, index=backtest_prices.index)
    months_elapsed = np.arange(len(port_series)) / 12
    expected_growth = initial_capital * (1 + wp_ret_ann/100) ** months_elapsed

    total_return = (port_series.iloc[-1] / port_series.iloc[0] - 1) * 100
    years = (backtest_prices.index[-1] - backtest_prices.index[0]).days / 365.25
    cagr  = ((port_series.iloc[-1] / port_series.iloc[0])**(1/years) - 1) * 100
    monthly_rets = port_series.pct_change().dropna()
    vol   = monthly_rets.std() * np.sqrt(12) * 100
    sharpe = (cagr/100 - 0.065) / (vol/100)

    # Metric cards
    cols = st.columns(4)
    metrics = [
        ("Total Return", f"{total_return:.1f}%", "positive" if total_return > 0 else "negative"),
        ("CAGR", f"{cagr:.2f}%", "positive" if cagr > 6.5 else "negative"),
        ("Realized Vol", f"{vol:.2f}%", "neutral"),
        ("Sharpe Ratio", f"{sharpe:.3f}", "positive" if sharpe > 1 else "negative"),
    ]
    for col, (label, value, cls) in zip(cols, metrics):
        with col:
            st.markdown(f'<div class="metric-card"><div class="metric-label">{label}</div>'
                        f'<div class="metric-value {cls}">{value}</div></div>',
                        unsafe_allow_html=True)

    st.markdown("")

    # Portfolio value chart
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=port_series.index, y=port_series.values,
                             name=strategy, line=dict(color="#3fb950", width=2)))
    fig.add_trace(go.Scatter(x=backtest_prices.index, y=expected_growth,
                             name=f"Expected Growth ({wp_ret_ann:.1f}% CAGR)",
                             line=dict(color="#f85149", width=2, dash="dash")))
    fig.add_hline(y=initial_capital, line_dash="dot", line_color="#8b949e",
                  annotation_text="Initial Investment")
    fig.update_layout(**PLOT_THEME, height=450,
                      xaxis_title="Date", yaxis_title="Portfolio Value (Base = 100)",
                      title=f"Portfolio Performance — {strategy}")
    st.plotly_chart(fig, use_container_width=True)

    # Monthly returns bar chart
    st.markdown('<div class="section-header">Monthly Returns</div>', unsafe_allow_html=True)
    fig2 = go.Figure(go.Bar(
        x=monthly_rets.index, y=monthly_rets.values*100,
        marker_color=["#3fb950" if r >= 0 else "#f85149" for r in monthly_rets],
    ))
    fig2.update_layout(**PLOT_THEME, height=300,
                       xaxis_title="Date", yaxis_title="Monthly Return (%)")
    st.plotly_chart(fig2, use_container_width=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE 5 — ROLLING SHARPE
# ════════════════════════════════════════════════════════════════════════════
elif page == "📉 Rolling Sharpe":
    st.title("Rolling Sharpe Ratio")
    st.markdown("##### 6-Month and 12-Month Windows vs Sharpe = 1 Benchmark")
    st.markdown("---")

    mu_target = (1.22)**(1/12) - 1
    w_wp = g + h * mu_target

    backtest_prices = prices[(prices.index >= "2021-01-01") & (prices.index <= "2025-06-30")]

    strategy = st.radio("Strategy", ["Buy-and-Hold", "Quarterly Rebalanced"], horizontal=True)

    if strategy == "Buy-and-Hold":
        shares = (100.0 * w_wp) / backtest_prices.iloc[0].values
        port_values = backtest_prices.values @ shares
    else:
        port_values = [100.0]
        shares = (100.0 * w_wp) / backtest_prices.iloc[0].values
        for i in range(1, len(backtest_prices)):
            cv = backtest_prices.iloc[i].values @ shares
            port_values.append(cv)
            if i % 3 == 0:
                shares = (cv * w_wp) / backtest_prices.iloc[i].values
        port_values = np.array(port_values)

    port_series   = pd.Series(port_values, index=backtest_prices.index)
    monthly_rets  = port_series.pct_change().dropna()

    def rolling_sharpe(rets, window):
        rm  = rets.rolling(window).mean() * 12
        rs  = rets.rolling(window).std()  * np.sqrt(12)
        return (rm - 0.065) / rs

    s6  = rolling_sharpe(monthly_rets, 6)
    s12 = rolling_sharpe(monthly_rets, 12)

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=s6.index, y=s6.values, name="6-Month Rolling",
                             line=dict(color="#3fb950", width=2)))
    fig.add_trace(go.Scatter(x=s12.index, y=s12.values, name="12-Month Rolling",
                             line=dict(color="#58a6ff", width=2)))
    fig.add_hline(y=1, line_dash="dash", line_color="#f85149",
                  annotation_text="Sharpe = 1", annotation_position="right")
    fig.add_hline(y=0, line_dash="dot", line_color="#8b949e")
    fig.update_layout(**PLOT_THEME, height=500,
                      xaxis_title="Date", yaxis_title="Sharpe Ratio (Annualised)",
                      title=f"Rolling Sharpe Ratio — {strategy}")
    st.plotly_chart(fig, use_container_width=True)

    col1, col2 = st.columns(2)
    for col, (label, s) in zip([col1, col2], [("6-Month", s6), ("12-Month", s12)]):
        with col:
            st.markdown(f'<div class="section-header">{label} Window Stats</div>',
                        unsafe_allow_html=True)
            valid = s.dropna()
            above = (valid > 1).sum()
            st.markdown(f"""
            - **Mean Sharpe:** {valid.mean():.3f}
            - **Min:** {valid.min():.3f}
            - **Max:** {valid.max():.3f}
            - **Months above 1:** {above} / {len(valid)}
            """)

# ════════════════════════════════════════════════════════════════════════════
# PAGE 6 — ESTRADA SEMIVARIANCE
# ════════════════════════════════════════════════════════════════════════════
elif page == "🔻 Semivariance (Estrada)":
    st.title("Estrada's Mean-Semivariance Framework")
    st.markdown("##### $D = w'\\Psi w$ · Semicovariance Matrix Approximation")
    st.markdown("---")

    # Analytical semivariance frontier using Psi
    ones    = np.ones(len(stocks))
    Psi_inv = np.linalg.inv(Psi)
    A_s = ones @ Psi_inv @ mean_ret
    B_s = mean_ret @ Psi_inv @ mean_ret
    C_s = ones @ Psi_inv @ ones
    D_s = B_s * C_s - A_s**2
    g_s = (1/D_s)*(B_s*(Psi_inv@ones) - A_s*(Psi_inv@mean_ret))
    h_s = (1/D_s)*(C_s*(Psi_inv@mean_ret) - A_s*(Psi_inv@ones))

    mu_gmv_s  = A_s / C_s
    w_gmv_s   = g_s + h_s * mu_gmv_s

    # MVP from standard variance
    mu_gmv   = A / C
    w_gmv    = g + h * mu_gmv
    ret_gmv  = ((1 + w_gmv @ mean_ret)**12 - 1) * 100
    mvp_semi = np.sqrt(w_gmv @ Psi @ w_gmv * 12) * 100
    mvp_vol  = np.sqrt(w_gmv @ cov_mat @ w_gmv * 12) * 100

    # Min semivariance point from MC
    min_semi_idx   = np.argmin(port_semidev)
    min_semi_point = (port_semidev[min_semi_idx], port_ret[min_semi_idx])

    col1, col2 = st.columns(2)

    with col1:
        st.markdown('<div class="section-header">Mean-Variance Frontier</div>',
                    unsafe_allow_html=True)
        fig1 = go.Figure()
        fig1.add_trace(go.Scatter(x=port_vol, y=port_ret, mode="markers",
                                  marker=dict(size=1, color="#1f6feb", opacity=0.3),
                                  name="Portfolios", hoverinfo="skip"))
        fig1.add_trace(go.Scatter(x=[mvp_vol], y=[ret_gmv], mode="markers",
                                  marker=dict(size=18, color="#58a6ff", symbol="star",
                                              line=dict(color="white", width=1)),
                                  name="MVP (Min Variance)"))
        fig1.update_layout(**PLOT_THEME, height=450,
                           xaxis_title="Std. Deviation (%)",
                           yaxis_title="Expected Return (%)")
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        st.markdown('<div class="section-header">Mean-Semivariance Frontier (Estrada)</div>',
                    unsafe_allow_html=True)
        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(x=port_semidev, y=port_ret, mode="markers",
                                  marker=dict(size=1, color="#1f6feb", opacity=0.3),
                                  name="Portfolios", hoverinfo="skip"))
        fig2.add_trace(go.Scatter(x=[mvp_semi], y=[ret_gmv], mode="markers",
                                  marker=dict(size=18, color="#58a6ff", symbol="star",
                                              line=dict(color="white", width=1)),
                                  name="MVP mapped via Estrada"))
        fig2.add_trace(go.Scatter(x=[min_semi_point[0]], y=[min_semi_point[1]],
                                  mode="markers",
                                  marker=dict(size=18, color="#f0883e", symbol="star",
                                              line=dict(color="white", width=1)),
                                  name="True Min Semi-Dev Portfolio"))
        fig2.update_layout(**PLOT_THEME, height=450,
                           xaxis_title="Semi-Deviation √(w'Ψw) (%)",
                           yaxis_title="Expected Return (%)")
        st.plotly_chart(fig2, use_container_width=True)

    # Verification table
    st.markdown('<div class="section-header">Estrada Approximation Verification</div>',
                unsafe_allow_html=True)

    downside_mvp = np.minimum(ret_mat @ w_gmv - (ret_mat @ w_gmv).mean(), 0)
    true_semi    = np.sqrt(np.mean(downside_mvp**2) * 12) * 100
    est_semi     = mvp_semi

    vdf = pd.DataFrame({
        "Method": ["True Semivariance (from return series)", "Estrada Approximation (w'Ψw)"],
        "Semi-Deviation (%)": [f"{true_semi:.4f}", f"{est_semi:.4f}"],
        "Difference (%)": ["—", f"{abs(true_semi - est_semi):.4f}"],
    })
    st.dataframe(vdf.set_index("Method"), use_container_width=True)
